import { Listing } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const ListingView: NextPage = () => {
  const router = useRouter();
  console.log(router.query.id);
  const listing = api.listings.get.useQuery(
    {
      listingId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );
  const listingItem = listing.data;
  if (!listingItem) {
    return;
  }

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 bg-gray-500">
        <div className="container mx-auto flex flex-col gap-12">
          <h1 className="mt-12 text-4xl">{listingItem.name}</h1>
          <p>{listingItem.description}</p>
          <p>$ {listingItem.price}</p>
        </div>
      </main>
    </>
  );
};

export default ListingView;
